### ISSUE TITLE
Xcode16 Missing '#include <sys/_types/_u_char.h>'; 'u_char' must be declared before it is used

### ISSUE THREAD

**Issue by lilongcnc** [amisare/BSDiff-iOS#1]
bspatch.c in Xcdoe16 beta
 error: Missing '#include <sys/_types/_u_char.h>'; 'u_char' must be declared before it is used

I use cocoapod Manage Projects。 please update it

**Comment by amisare** [comment]
update bsdiff-ios version: 4.3.0.2
